import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import jsxA11y from "eslint-plugin-jsx-a11y";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import eslintComments from "@eslint-community/eslint-plugin-eslint-comments";
import checkFile from "eslint-plugin-check-file";
import jsdoc from "eslint-plugin-jsdoc";
import boundaries from "eslint-plugin-boundaries";
import vitest from "@vitest/eslint-plugin";
import testingLibrary from "eslint-plugin-testing-library";
import playwright from "eslint-plugin-playwright";
import prettier from "eslint-config-prettier";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  // `database.types.ts` is generated by the Supabase CLI; don't lint it.
  globalIgnores([
    "dist",
    "src-tauri/target",
    "src/lib/database.types.ts",
    "coverage",
    "playwright-report",
    "test-results",
  ]),

  // Application source: full type-aware linting.
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      jsxA11y.flatConfigs.strict,
    ],
    plugins: {
      "simple-import-sort": simpleImportSort,
      "@eslint-community/eslint-comments": eslintComments,
    },
    // Flag `eslint-disable` directives that no longer suppress anything so they
    // get cleaned up instead of silently rotting.
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      // Every `eslint-disable` directive must carry an inline `-- reason` so the
      // justification travels with the suppression instead of rotting nearby.
      "@eslint-community/eslint-comments/require-description": [
        "error",
        { ignore: [] },
      ],
      // Identifier casing. Types are PascalCase; values are camelCase with
      // PascalCase allowed for React components/constructors and UPPER_CASE for
      // module-level constants. Object/type members are left unchecked because
      // they routinely mirror external (DB/API/CSS) key casing. A leading
      // underscore (intentional discard) is always permitted.
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "default",
          format: ["camelCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: "variable",
          format: ["camelCase", "PascalCase", "UPPER_CASE"],
          leadingUnderscore: "allow",
        },
        {
          selector: "function",
          format: ["camelCase", "PascalCase"],
        },
        {
          selector: "parameter",
          format: ["camelCase", "PascalCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: "typeLike",
          format: ["PascalCase"],
        },
        {
          selector: "import",
          format: ["camelCase", "PascalCase"],
        },
        {
          // External-facing shapes (DB rows, API payloads, CSS-in-JS, etc.)
          // dictate their own key casing.
          selector: ["objectLiteralProperty", "typeProperty"],
          format: null,
        },
        {
          // Object-literal "methods" are often React component render-props
          // (e.g. a `components={{ Row, Emoji }}` map), so PascalCase is allowed.
          selector: "objectLiteralMethod",
          format: ["camelCase", "PascalCase"],
        },
      ],
      // Discard-by-destructuring and intentionally-unused params are signalled
      // with a leading underscore.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Allow async handlers to be passed to void-returning event props (a
      // pervasive React pattern); still catch genuinely unawaited promises in
      // statement position.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      // Numbers/booleans interpolate cleanly into strings; only object/any/never
      // interpolation is genuinely suspicious.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      // `str || fallback` (collapsing "" to a fallback) and boolean truthiness
      // chains are intentional here; keep the rule for object/number nullables.
      "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        { ignorePrimitives: { string: true, boolean: true } },
      ],
      // The app deliberately autofocuses inputs in dialogs and command menus
      // (standard focus management when a transient surface opens).
      "jsx-a11y/no-autofocus": "off",
      // Disabled deliberately: with the editor/DOM/ProseMirror types being more
      // optimistic than runtime reality, this rule produces frequent false
      // positives and would push us to strip defensive guards that are also
      // needed for type narrowing. The safety it adds isn't worth that risk here.
      "@typescript-eslint/no-unnecessary-condition": "off",
      // Keep `x as T` (unavoidable with loosely-typed libs) but forbid
      // object-literal casts (`{ ... } as T`), which silently mask missing or
      // misspelled properties; use a typed variable or `satisfies` instead.
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        { assertionStyle: "as", objectLiteralTypeAssertions: "never" },
      ],
      // Ban `as unknown` double-casts: they punch a hole through the type
      // system to force an otherwise-impossible assertion. Model the type
      // (or use a type guard) instead.
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSAsExpression > TSUnknownKeyword",
          message:
            "Avoid `as unknown` double-casts; model the type or use a type guard instead.",
        },
        {
          // Enforce the "Tokens, never raw values" design rule for `className`
          // string literals: a raw Tailwind palette color (e.g. `text-red-600`,
          // `bg-emerald-500`) has no light/dark pair and bypasses the theme.
          // Use a theme token (`text-danger`, `bg-success`, `text-muted`, ...).
          // Only catches literals (colors composed via variables slip through).
          selector:
            "JSXAttribute[name.name='className'] Literal[value=/\\b(?:text|bg|border|ring|fill|stroke|from|via|to|divide|outline|decoration|accent|caret|shadow)-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\\d{2,3}\\b/]",
          message:
            "Use a theme token (bg-surface, text-muted, text-danger, bg-success) instead of a raw Tailwind palette color; every color needs a light/dark pair.",
        },
      ],
      // Native dialogs (`window.alert`/`confirm`/`prompt`) are jarring and
      // unstyled inside the desktop shell; use an in-app dialog/popover instead.
      "no-alert": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      // Non-sibling imports go through the `@/` alias; only same-directory
      // `./` paths stay relative. Keeps deep `../../../` chains out of the tree.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["../*", "../**"],
              message:
                "Use the '@/' alias instead of parent-relative ('../') imports.",
            },
          ],
        },
      ],
    },
  },

  // Tiptap extensions interface with the library's loosely-typed (`any`) node
  // attribute and schema callbacks, so the no-unsafe-* family is unavoidable
  // noise here. Scope it off rather than littering inline disables.
  {
    files: ["src/editor/extensions/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  // File and folder naming. Everything under `src/` is kebab-case - both files
  // and folders - regardless of what the module exports (a `BookView` component
  // still lives in `book-view.tsx`). `ignoreMiddleExtensions` validates the
  // base name only, so suffixes like `.test.tsx`, `.module.css`, and `.d.ts`
  // pass on their stem (e.g. `vite-env.d.ts`, `database.types.ts`).
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.d.ts"],
    plugins: { "check-file": checkFile },
    rules: {
      "check-file/folder-naming-convention": [
        "error",
        { "src/**/": "KEBAB_CASE" },
      ],
      "check-file/filename-naming-convention": [
        "error",
        { "src/**/*.{ts,tsx}": "KEBAB_CASE" },
        { ignoreMiddleExtensions: true },
      ],
    },
  },

  // Require a JSDoc block on the exported API of the non-component layers
  // (data/lib/fonts/store and editor utility modules). TypeScript already
  // carries the types, so only a description block is required - param/return
  // type tags are off, and `no-types` forbids redundant `{type}` annotations.
  {
    files: [
      "src/data/**/*.ts",
      "src/lib/**/*.ts",
      "src/fonts/**/*.ts",
      "src/store/**/*.ts",
      "src/editor/**/*.ts",
    ],
    ignores: ["src/**/*.d.ts", "src/**/*.test.ts", "src/**/*.test.tsx"],
    plugins: { jsdoc },
    settings: { jsdoc: { mode: "typescript" } },
    rules: {
      "jsdoc/require-jsdoc": [
        "error",
        {
          // Only the exported API needs docs - not internal helpers. Disable
          // the default "every FunctionDeclaration" requirement and rely solely
          // on the export-scoped contexts below.
          require: { FunctionDeclaration: false },
          contexts: [
            "ExportNamedDeclaration > FunctionDeclaration",
            "ExportNamedDeclaration > TSInterfaceDeclaration",
            "ExportNamedDeclaration > TSTypeAliasDeclaration",
          ],
        },
      ],
      "jsdoc/require-param": "off",
      "jsdoc/require-returns": "off",
      "jsdoc/no-types": "error",
      "jsdoc/check-alignment": "error",
    },
  },

  // Architectural boundaries between the top-level `src/` layers. The allowed
  // dependency graph below was validated against the real import graph (see the
  // audit canvas); it locks the lower layers (lib/store/theme/data/fonts) so
  // they can't reach up into UI code, while reflecting the existing two-way
  // components<->editor relationship (shared UI primitives live in components).
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/**/*.d.ts",
      "src/**/*.test.ts",
      "src/**/*.test.tsx",
      "src/test/**",
    ],
    plugins: { boundaries },
    settings: {
      "import/resolver": {
        typescript: { alwaysTryTypes: true, project: "tsconfig.app.json" },
      },
      "boundaries/elements": [
        { type: "lib", pattern: "src/lib", mode: "folder" },
        { type: "store", pattern: "src/store", mode: "folder" },
        { type: "theme", pattern: "src/theme", mode: "folder" },
        { type: "fonts", pattern: "src/fonts", mode: "folder" },
        { type: "data", pattern: "src/data", mode: "folder" },
        { type: "editor", pattern: "src/editor", mode: "folder" },
        { type: "components", pattern: "src/components", mode: "folder" },
        { type: "app", pattern: "src/*.{ts,tsx}", mode: "full" },
      ],
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          rules: [
            // The app entrypoints may wire anything together.
            { from: { type: "app" }, allow: { to: { type: "*" } } },
            {
              from: { type: "components" },
              allow: {
                to: {
                  type: ["editor", "data", "fonts", "store", "theme", "lib"],
                },
              },
            },
            {
              from: { type: "editor" },
              allow: { to: { type: ["components", "data", "store", "lib"] } },
            },
            {
              from: { type: "data" },
              allow: { to: { type: ["fonts", "lib"] } },
            },
            {
              from: { type: "fonts" },
              allow: { to: { type: ["data", "lib"] } },
            },
            // Leaf layers may only reach down to the shared `lib` utilities.
            { from: { type: "store" }, allow: { to: { type: ["lib"] } } },
            { from: { type: "theme" }, allow: { to: { type: ["lib"] } } },
          ],
        },
      ],
    },
  },

  // Node-side config/build files.
  {
    files: ["*.{js,ts}", "vite.config.ts"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Tests and the shared test harness. Wire up the Vitest / Testing Library /
  // jest-dom lint plugins and relax a few production-only rules that fight with
  // test ergonomics (render helpers export non-components; fixtures lean on
  // non-null assertions).
  {
    files: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    extends: [vitest.configs.recommended, testingLibrary.configs["flat/react"]],
    languageOptions: {
      globals: vitest.environments.env.globals,
    },
    rules: {
      "react-refresh/only-export-components": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      // Test helpers and fixtures routinely wrap loosely-typed libraries and
      // mock payloads; the no-unsafe-* family is noise here (mirrors the
      // editor-extensions carve-out above).
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  // Playwright end-to-end specs and their fixtures.
  {
    files: ["e2e/**/*.ts"],
    extends: [playwright.configs["flat/recommended"]],
    rules: {
      // Playwright fixtures take a `use` callback param, which the React Hooks
      // plugin misreads as a call to React 19's `use` hook.
      "react-hooks/rules-of-hooks": "off",
    },
  },

  // Disable stylistic rules that conflict with Prettier. Must come last.
  prettier,
]);
