import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import jsxA11y from "eslint-plugin-jsx-a11y";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import prettier from "eslint-config-prettier";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  // `database.types.ts` is generated by the Supabase CLI; don't lint it.
  globalIgnores(["dist", "src-tauri/target", "src/lib/database.types.ts"]),

  // Application source: full type-aware linting.
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      jsxA11y.flatConfigs.recommended,
    ],
    plugins: {
      "simple-import-sort": simpleImportSort,
    },
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      // Discard-by-destructuring and intentionally-unused params are signalled
      // with a leading underscore.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Allow async handlers to be passed to void-returning event props (a
      // pervasive React pattern); still catch genuinely unawaited promises in
      // statement position.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      // Numbers/booleans interpolate cleanly into strings; only object/any/never
      // interpolation is genuinely suspicious.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      // `str || fallback` (collapsing "" to a fallback) and boolean truthiness
      // chains are intentional here; keep the rule for object/number nullables.
      "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        { ignorePrimitives: { string: true, boolean: true } },
      ],
      // The app deliberately autofocuses inputs in dialogs and command menus
      // (standard focus management when a transient surface opens).
      "jsx-a11y/no-autofocus": "off",
      // Disabled deliberately: with the editor/DOM/ProseMirror types being more
      // optimistic than runtime reality, this rule produces frequent false
      // positives and would push us to strip defensive guards that are also
      // needed for type narrowing. The safety it adds isn't worth that risk here.
      "@typescript-eslint/no-unnecessary-condition": "off",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },

  // Tiptap extensions interface with the library's loosely-typed (`any`) node
  // attribute and schema callbacks, so the no-unsafe-* family is unavoidable
  // noise here. Scope it off rather than littering inline disables.
  {
    files: ["src/editor/extensions/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  // Node-side config/build files.
  {
    files: ["*.{js,ts}", "vite.config.ts"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Disable stylistic rules that conflict with Prettier. Must come last.
  prettier,
]);
